### ISSUE TITLE
Wrong file path used by wsimport

### ISSUE THREAD

**Issue by christiangoudreau** [boothen/gradle-wsimport#11]
The generated service use the absolute filepath of the wsdlwhich makes it unusable when deployed to another computer...

Couldn't we use a classpath or is there something I missed?

Thanks and best regards,

**Comment by boothen** [comment]
HI @christiangoudreau,

I'm not quite understanding your issue sorry. Could you provide an example of what you mean?

I would have thought that everything is generated based off the resource and build folders specified.

**Comment by christiangoudreau** [comment]
Well, it was a code 18. Sorry :D I found was I was looking for! 

Thanks!
