### ISSUE TITLE
Error output never shown

### ISSUE THREAD

**Issue by castoglobant** [boothen/gradle-wsimport#13]
Iam using the latest version with gradle 5/6 but no see any output for any error or successful build. Using the jaxb directly is posible see the wsimport output. Is posible I am doing anything wrong with the plugin or this need any gradle plugin API update & rebuild?

**Comment by boothen** [comment]
Hi @castoglobant,

The plugin should work fine with both Gradle 5/6. Is it possible you could post your build configuration relating to the plugin?

Cheers,
Matt.

**Comment by deepfunction** [comment]
Hello. My gradle. No any files in output, but task successful.

plugins {
    id 'java'
    id 'io.quarkus'
    id "uk.co.boothen.gradle.wsimport" version "0.16"
}

repositories {
    mavenLocal()
    mavenCentral()
}

wsimport {
    wsdl = "create/DispensaryService.wsdl"
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-arc'
    testImplementation 'io.quarkus:quarkus-junit5'
}

group 'su.medsoft'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

**Comment by castocolina** [comment]
Hello @boothen,

Sorry for the delay. Here a sample code. Check jaxb task work OK but i only get fail from wsimport plugin.

My sample at: https://github.com/castocolina/demo-soap-spring-client/blob/master/build.gradle

In my original project the plugin dint show output for anything success or error.

```
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.6.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    id 'java'

    // Apply the application plugin to add support for building a CLI application.
    id 'application'

    id "de.undercouch.download" version "4.0.4"
    id "uk.co.boothen.gradle.wsimport" version "0.16"
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

// tag::configurations[]
configurations {
    jaxb
}
// end::configurations[]

repositories {
    mavenCentral()
}


application {
    // Define the main class for the application.
    mainClassName = 'demo.soap.spring.client.App'
}

task downloadWSDL(type: Download) {
    src 'http://127.0.0.1:8080/ws/countries.wsdl'
    dest "src/main/resources/"
}

// tag::wsdl[]
task genJaxb {
    ext.sourcesDir = "${buildDir}/generated-sources/jaxb"
    ext.classesDir = "${buildDir}/classes/jaxb"
    ext.schema = "src/main/resources/countries.wsdl"

    outputs.dir classesDir

    doLast() {
        project.ant {
            taskdef name: "xjc", classname: "com.sun.tools.xjc.XJC2Task",
                    classpath: configurations.jaxb.asPath
            mkdir(dir: sourcesDir)
            mkdir(dir: classesDir)

            xjc(destdir: sourcesDir, schema: schema,
                    package: "com.example.consumingwebservice.wsdl") {
                arg(value: "-wsdl")
                produces(dir: sourcesDir, includes: "**/*.java")

            }

            javac(destdir: classesDir, source: 11, target: 11, debug: true,
                    debugLevel: "lines,vars,source",
                    classpath: configurations.jaxb.asPath) {
                src(path: sourcesDir)
                include(name: "**/*.java")
                include(name: "*.java")
            }

            copy(todir: classesDir) {
                fileset(dir: sourcesDir, erroronmissingdir: false) {
                    exclude(name: "**/*.java")
                }
            }
        }
    }
}
// end::wsdl[]


wsimport {
    // wsdlSourceRoot = "src/main/resources/"
    // generatedSourceRoot = "/generated-sources/wsdl"
    // generatedClassesRoot = "/classes/wsdl"
//	target = "2.2"
//	keep = true
//	extension = true
//	verbose = true
//	quiet = false
//	debug = true
//	xnocompile = true
    wsdl = "src/main/resources/countries.wsdl"
}

dependencies {
    // This dependency is used by the application.
    // implementation 'com.google.guava:guava:29.0-jre'

    // For Java 11:
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.3'
    implementation(files(genJaxb.classesDir).builtBy(genJaxb))
    jaxb "com.sun.xml.bind:jaxb-xjc:2.3.3"

    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'
}
```

**Comment by boothen** [comment]
Hi @castocolina,

The error messaging is really poor in the plugin atm. To define the location of the WSDL directly under `/src/main/resources` like you have you just need the following:

```
wsimport {
    wsdlSourceRoot = "src/main/resources/"
    wsdl = "countries.wsdl"
}
```

The plugin has a default location for the WSDL as `/src/main/resources/wsdl`. If you move your WSDL into that location then you can just have

```
wsimport {
    wsdl = "countries.wsdl"
}
```
for the definition. 

I'll add some logic around validating that the files and directory locations exists to help with this kind of issue in the future.

Cheers,
Matt.
