### ISSUE TITLE
Do not add dependencies to "implementation"

### ISSUE THREAD

**Issue by Vampire** [boothen/gradle-wsimport#16]
Please do not add dependencies to "implementation" or at least make it optional.
If you for example use jaxws tools 3.0.0 you might need completely different dependencies.
Imho the plugin should concentrate on generating source from wsdl only.

**Comment by boothen** [comment]
Hi @Vampire,

I've add an option to not add the implementation dependencies in 0.18. Let me know if this works as expected.

Cheers,
Matt.
