### ISSUE TITLE
Only define default dependencies for jaxWsTools configuration

### ISSUE THREAD

**Issue by Vampire** [boothen/gradle-wsimport#17]
If you don't register the `jaxWsTools` configuration in an `afterEvaluate` block, but eagerly and define default dependencies instead of normal dependencies, one can easily define the exact tools to be used in the build script.

**Comment by boothen** [comment]
Hi @Vampire,

I've changed this to define default dependencies in 0.18. Let me know if this works as expected?

Cheers,
Matt.
