### ISSUE TITLE
wsimport 0.16 version plugin issue

### ISSUE THREAD

**Issue by fog26** [boothen/gradle-wsimport#20]
Hello, I am using java 1.8 + Greadle 6.4.1 with wsimport plugin 0.16.

Did anyone had the similar issue: 
"java.lang.UnsupportedClassVersionError: uk/co/boothen/gradle/wsimport/WsImportPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0
), this version of the Java Runtime only recognizes class file versions up to 52.0"  ?

Update: it seems like the versions starting from 0.12 were compiled with Java 11, so I've tried to use 0.11. and now in the part of the build.gradle file where you put omptions:
.........
wsimport {
     wsdlSourceRoute = "src/..../wsdl"
     wsdl = "nameOfTheWsdlFile.wsdl"
     generatedSourceRoot = "generated/src/wsdl/main"
     generatedClassesRoot = "/classes.main"
}

I get his kind of error:
- Could not find method wsimport() for arguments [buld.......] on root project 'ProjectName' of type org.gradlle.api.Project.

Any idea how to resolve it? Also maybe version 0.11 has different way to generate those classes?

**Comment by fog26** [comment]
which of the version is supported by java 8?

**Comment by boothen** [comment]
Hi, if I remember correctly you need to specify it as a task, so

```
task wsimport(type: uk.co.boothen.gradle.wsimport.WsImport) {
   wsdlSourceRoot = "src/..../wsdl"
   wsdl = "nameOfTheWsdlFile.wsdl"
   generatedSourceRoot = "generated/src/wsdl/main"
   generatedClassesRoot = "/classes.main"
}
```

Cheers,
Matt.
