### ISSUE TITLE
Reading wsdl files from http/https sources

### ISSUE THREAD

**Issue by INeedMySpace** [boothen/gradle-wsimport#25]
Hello nice people. 
In our project we use wsimport Ant task and when I found your plugin I decided to give it a try but found out that we could not use http/https urls as a source for wsdl files.
Original WsImport task works well with remote http/https located wsdls.
As I see in `WsImportPlugin.java:66` you prepend wsdlSourceRoot with projectDir.
I would suggest if wsdlSourceRoot start with http:// or https:// to use it as is.
Kind Regards, Aleks.

**Comment by INeedMySpace** [comment]
Was not able to create branch and PR (I'm not sure wether it's repository restrictions or issue on my side).
Could be fixed with following:
`String wsdlSourceRoot = wsImportPluginExtension.getWsdlSourceRoot().matches("(?i)^(http|https)://.*") ?
      wsImportPluginExtension.getWsdlSourceRoot() :
      Util.mergePaths(project.getProjectDir().getAbsolutePath(), wsImportPluginExtension.getWsdlSourceRoot());`

**Comment by boothen** [comment]
Hi @INeedMySpace,

There shouldn't be any issue creating a new branch and submitting a PR.

I'll add in your changes and submit the new Plugin version. It normally take a day or so for it to be improved. I'll let you know when it's there.

Cheers,
Matt.

**Comment by boothen** [comment]
Version 0.20 has been published to https://plugins.gradle.org/plugin/uk.co.boothen.gradle.wsimport.

Let me know if it works as expected.

Cheers,
Matt.

**Comment by INeedMySpace** [comment]
Hi, Matt!
Sorry for delayed response. I tried 0.20 version.
It generates sources from http link.
But the task itself reports to be failed.
```
> A failure occurred while executing uk.co.boothen.gradle.wsimport.WsImportWorkAction
   > wsimport failed
```
I'm not sure wether it is related issued. Adding 
```
verbose = true
    quiet = false
    debug = true
    xdebug = true
```
didn't help much with quick glance. Also adding --debug to gradlew didn't provided any hints why it's failed.
```
2023-07-04T11:51:17.086+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: wsimport failed
2023-07-04T11:51:17.086+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:466)
2023-07-04T11:51:17.086+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.ws.ant.WsImportBase.execute(WsImportBase.java:552)
2023-07-04T11:51:17.086+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at uk.co.boothen.gradle.wsimport.WsImportWorkAction.execute(WsImportWorkAction.java:96)
```

Cheers, Aleks.

**Comment by boothen** [comment]
Hi Aleks,

I'll look into why the log details are not being displayed. Hopefully, that will help to determine the cause of your issue. Could you share your task configuration? I'm guessing the urls for the WSDLs you can't share though?

Cheers,
Matt.

**Comment by INeedMySpace** [comment]
Hi Matt. I think I can post it in simplified form - test build.gradle.kts project:
```
plugins {
    kotlin("jvm") version "1.8.22"
    id("uk.co.boothen.gradle.wsimport") version "0.20"
}

group = "local"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

wsimport {
    wsdlSourceRoot = "https://portal.mvp.bafin.de:444/services/ws/"
    generatedSourceRoot = "generated-a26mifir"
    generatedClassesRoot = "/classes/java/main"

    keep = true
    verbose = true
    quiet = false
    debug = true
    xdebug = true
    xnocompile = false
    xadditionalHeaders = false

    wsdl ("a26mifir?wsdl") {
        xjcarg("-XautoNameResolution")
        extraArg("-J-Djavax.xml.accessExternalDTD=all")
        packageName("generated.bafin.a26mifir")
    }
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(17)
}
```
Cheers, Aleks

**Comment by boothen** [comment]
Hi Aleks,

Thanks for the details. I've managed to resolve the displaying of the debug details. You should just need to specify

```
verbose = true
quiet = false
debug = true
xdebug = true
```
to see the execution info from the WsImport task.

I think I may have resolved your issue as well although can't be sure. If you add `extraArg("-J-Djavax.xml.accessExternalSchema=all") `it may resolve your issue. When I ran your configuration there was a warning about needing to enable accessExternalSchema for https.

Try 0.21 and let me know how you get on.

Cheers,
Matt.

**Comment by INeedMySpace** [comment]
Thanks a lot Matt. 0.21 works for me now and I can see debug output!
