### ISSUE TITLE
Multiple wsdl files only processes the first one.

### ISSUE THREAD

**Issue by megazone23** [boothen/gradle-wsimport#26]
I have multiple wsdl files specified like this...

wsimport {
    verbose = true
    xdebug = true
    debug = true
    keep = true
    generatedSourceRoot = '../src/main/java'
    wsdl ("gen/Service1.wsdl") {
       packageName("com.service1")
       xjcarg ("-XautoNameResolution")
    }
    wsdl ("oerp/Service2.wsdl") {
       packageName("com.service2")
       xjcarg ("-XautoNameResolution")
    }
}

Only Service1 files are generated.  It looks like Service2 is ignored.

**Comment by megazone23** [comment]
I think I figued out what was going wrong.  I had multiple top level wsimport tasks.  Once I removed the other one it started working correctly.

**Comment by boothen** [comment]
Yeah, you only can have one per module.

Cheers,
Matt.
