### ISSUE TITLE
How to set typesafeEnumMaxMembers and generateMixedExtensions?

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [boothen/gradle-wsimport#28]
Hello I have a wsdl which has about 300 Enum constants for a field...
By default the maximum amount of enum values is 256...

In addition to that the WSDL also uses mixed=true complex types in its XSD schemas.

Normally one would create a .xjb file and pass that using -b to wsimport.

wsdl("rahulsom_ihe_iti/iti/wsdl/PIXManager.wsdl") {
    packageName = "ch.imagic.soap.generated.iti45"
    bindingFiles = listOf("rahulsom_ihe_iti/iti/wsdlbind/jaxws.xjb")
}

This is from my gradle file and if the xjb does not exist (by giving it a fake name) the build fails. So it does something with this file...
This is the content of the XJB file:
```
<jaxws:bindings
    xmlns:jaxws="http://java.sun.com/xml/ns/jaxws"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
    jaxb:version="2.0">
  <jaxws:enableAsyncMapping>true</jaxws:enableAsyncMapping>

  <jaxws:bindings>
    <jaxb:globalBindings typesafeEnumMaxMembers="2000" generateMixedExtensions="true"/>
  </jaxws:bindings>
  <jaxb:bindings >
    <jaxb:globalBindings typesafeEnumMaxMembers="2000" generateMixedExtensions="true"/>
  </jaxb:bindings>

</jaxws:bindings>
```

I still get this warning about too many enum values and it tells me to use typesafeEnumMaxMembers:
[wsImport] [WARNING] Einfacher Typ "NativeEntityContiguous" war Enum wegen EnumMemberSizeCap-Grenzwert nicht zugeordnet. Anzahl Facets: 337, aktueller Grenzwert: 256. Sie können das Anpassungsattribut "typesafeEnumMaxMembers" verwenden, um den Grenzwert zu erweitern.
(sorry for german error, my system language is german)

In addition to that the data type with the mixed=true should have:

@XmlMixed
protected List<Serializable> content;

but it does not!

I am using 
target = "2.2"
and jaxWsTools("com.sun.xml.ws:jaxws-tools:2.3.5")

Help with this would be greatly appreciated!
Sincerely
Alexander Schütz

**Comment by boothen** [comment]
Hi @AlexanderSchuetz97 

Have you tried `bindingFile = "rahulsom_ihe_iti/iti/wsdlbind/jaxws.xjb"`? The parameter is specified without an s.

Cheers,
Matt.

**Comment by AlexanderSchuetz97** [comment]
Hi
Turns out my XJB was just invalid.
It took hours of debugging to find but yeah
after using this XJB:
```
<?xml version="1.0" ?>
<bindings version="1.0" xmlns="http://java.sun.com/xml/ns/jaxb">
        <bindings>
            <globalBindings typesafeEnumMaxMembers="1000" generateMixedExtensions="true"/>
        </bindings>
</bindings>
```
it worked... sorry for bothering you
Sincerely
Alexander Schütz
