### ISSUE TITLE
No Java plugin detected error... in a Groovy subproject

### ISSUE THREAD

**Issue by mauromol** [boothen/gradle-wsimport#3]
I have a Gradle multiproject, flat layout:

- master
- groovySubproject

The subproject groovySubproject applies the wsimport plugin and the Groovy plugin:

```groovy
plugins {
	id 'uk.co.boothen.gradle.wsimport' version '0.4'
}

apply plugin: 'groovy'
```

This makes the build fail with:
Failed to apply plugin [id 'uk.co.boothen.gradle.wsimport']
No java plugin detected. Enable java plugin.

I suspect the plugin tries to detect the Java plugin on the master project and fails. In my case, the master project does not apply the Java plugin and does not need to.

I don't think the problem lies in the groovySubproject: I also tried to apply the java plugin there, with no success.

Tried with both Gradle 4.2 and 4.10.3 wrappers.

**Comment by andershermansen** [comment]
This error happened to me as well, but on a single project. Try to apply the wsimport after groovy:
```
plugins {
	id 'uk.co.boothen.gradle.wsimport' version '0.4'  apply false
}

apply plugin: 'groovy'
apply plugin: 'uk.co.boothen.gradle.wsimport'
```

I'm not sure about the reason or proper fix. This is just suggested as a workaround.

**Comment by boothen** [comment]
The plugin was checking for the JavaPlugin during the apply stage. I've changed this to check only when an WsImport task is defined.

The fix is in version 0.6 of the plugin.

Could you verify if this has fixed the issue for you?

Thanks.

**Comment by andershermansen** [comment]
@boothen Thanks, this fixed the issue for me. build.gradle file looks cleaner now :)

**Comment by boothen** [comment]
Brilliant. Thanks. I'll close this issue.
