### ISSUE TITLE
When declaring multiple wsdl files only the first one is processed

### ISSUE THREAD

**Issue by mrodal** [boothen/gradle-wsimport#30]
Like reported on this issue: https://github.com/boothen/gradle-wsimport/issues/26
Only that I dont have multiple top level wsimport tasks. Here's my only task:

```
wsimport {
    includeDependencies = false
    target = "2.2"

    wsdl "service1.wsdl"
    wsdl "service2.wsdl"
}
```

If I comment out the service1 line, then it processes service2.wsdl

**Comment by boothen** [comment]
Hi @mrodal,

Might be something simple like using equals when assigning the wsdl files. i.e.

```
wsimport {
    includeDependencies = false
    target = "2.2"

    wsdl = "service1.wsdl"
    wsdl = "service2.wsdl"
}
```

I can't see why it isn't working otherwise.

Cheers,
Matt.

**Comment by mrodal** [comment]
Hi @boothen , Its still doing the same 😕
Is it working correctly for you? I tried with a empty project and the issue remains, this is the whole build.gradle:

```gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.2'
    id 'io.spring.dependency-management' version '1.1.4'
    id "uk.co.boothen.gradle.wsimport" version "0.21"
}

group = 'com.santander.ws-demo'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-web-services'
    implementation 'org.springframework.ws:spring-ws-security'
    implementation 'org.apache.ws.security:wss4j:1.6.19'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

wsimport {
    wsdl = "service1.wsdl"
    wsdl = "service2.wsdl"
}
```

**Comment by boothen** [comment]
What version of Gradle are you using?
Have you tried setting different packages for each wsdl? Just in case there's a naming clash causing the issue.

```
wsimport {
    wsdl ("service1.wsdl") {
        packageName("com.different.package.service1")
    }
    wsdl ("service2.wsdl") {
        packageName("com.different.package.service2")
    }
}
```

**Comment by mrodal** [comment]
The issue persists, only the first one is processed..
I tried with both gradle 8.5 and 7.2, same behaviour

**Comment by boothen** [comment]
If you add

```
    verbose = true
    quiet = false
    debug = true
    xdebug = true
```

can you see 2nd file being processed?

**Comment by mrodal** [comment]
Found the issue, I was executing this task:
![image](https://github.com/boothen/gradle-wsimport/assets/20667544/7ead9d22-22da-4834-902d-e24e656cdda8)

Didnt know I had to gradle sync for new tasks to be generated for each file
![image](https://github.com/boothen/gradle-wsimport/assets/20667544/71b4d720-8844-4ed4-a673-b6f27bc21cac)

Thank you for the help!
