### ISSUE TITLE
Missing dependencies after update

### ISSUE THREAD

**Issue by jvs64893** [boothen/gradle-wsimport#8]
I just updated the plugin to version 0.11 and Gradle to version 5.6.3.

Everything worked before, but now dependencies seem to be missing to get the compilation working.

I get errors like the following:
```
 error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlType;
                                ^
```

**Comment by boothen** [comment]
I've explicitly added the compile the dependencies for the generated classes. Could you use version 0.12 to see if that's fixed it?

**Comment by jvs64893** [comment]
Thanks for your quick response. Sadly that didn't fix it, same error occurs using version 0.12.

**Comment by boothen** [comment]
Are they the exact same errors or fewer? It could be another dependency I need to add that my test files don't generate.

**Comment by jvs64893** [comment]
It's the same actually.

These are missing for example:
```
javax.xml.bind.annotation.XmlRootElement;
javax.xml.bind.annotation.XmlSchemaType;
javax.xml.bind.annotation.XmlType;
javax.xml.bind.annotation.XmlAccessType;
javax.xml.bind.annotation.XmlAccessorType;
javax.xml.bind.annotation.XmlElement;
javax.xml.bind.annotation.XmlEnum;
javax.xml.bind.annotation.XmlEnumValue;
```
There might be more, but I guess this can be a starting point.

edit:
I'm using Java 11 by the way, if that's some kind of Java 9+ module problem.

**Comment by boothen** [comment]
Strange. I can reproduce your problem with 0.11. However, with 0.12 those classes are being added as dependencies by the plugin and see the issue resolved.

If you run 
`
./gradlew -q dependencies
`
in the module using the plugin, you should hopefully see the following jars amongst the compile dependencies.

```
compileClasspath - Compile classpath for source set 'main'.
+--- javax.xml.bind:jaxb-api:2.3.1
|    \--- javax.activation:javax.activation-api:1.2.0
+--- javax.xml.ws:jaxws-api:2.3.1
|    +--- javax.xml.bind:jaxb-api:2.3.1 (*)
|    +--- javax.xml.soap:javax.xml.soap-api:1.4.0
|    \--- javax.annotation:javax.annotation-api:1.3.2
\--- javax.jws:javax.jws-api:1.1
```

But at the moment, I'm at a loss as to why 0.12 didn't fix your problem.

**Comment by jvs64893** [comment]
These are all available exactly as you stated under "compileClasspath". Is there a way to check which jars are added to the classpath when executing a WsImport task?

**Comment by boothen** [comment]
It is those Jars that are being added by the WsImport task. If you switch back to 0.11 and run the same command you'll see they don't appear. 

Is it possible you can post your wsimport task configuration? I can only guess that there's something different in that which means the compileClasspath jars are being ignored/not used by the generated classes.

**Comment by jvs64893** [comment]
Task:
```
task wsimportTest(type: uk.co.boothen.gradle.wsimport.WsImport) {
  group = "build"
  description = "Test generation"
  wsdl("test.wsdl") {
    bindingFile("binding.xml")
  }
}
```
binding.xml:
```
<?xml version="1.0" encoding="UTF-8"?> 
<bindings xmlns="http://java.sun.com/xml/ns/jaxb"
          version="2.1"> 
    <globalBindings choiceContentProperty="true"/> 
</bindings>
```

**Comment by boothen** [comment]
Ah. If you add 
```
xnocompile = true
```
the generated Java source will be compiled by Gradle instead of the WsImport task so should use the dependencies the plugin defines.

I'll investigate if it's possible for the plugin to work with that option set to false or at least give meaningful error feedback if it can't.

**Comment by jvs64893** [comment]
This works, thank you. Nonetheless this is more a workaround I guess.
