### ISSUE TITLE
compileJava.dependsOn not working

### ISSUE THREAD

**Issue by jvs64893** [boothen/gradle-wsimport#9]
Starting with version 0.13 the plugin prevents the following to work:
`compileJava.dependsOn $ANYTASK`

The given task is not added as a dependency to compileJava.

I think the problem is this change, which overwrites these dependencies:
https://github.com/boothen/gradle-wsimport/commit/3a7d37cc72de5bf4b6e264499a2c19c58919618e#diff-bbffbea3e6ceb6b26dff88a4241fda57R78

**Comment by boothen** [comment]
Hi @jvs64893,

Sorry about that. It's an obvious issue looking at the change. I've published a fix for this in 0.14 by reverting back to using dependsOn.

Hopefully, it fixes the problem.

Thanks.

**Comment by jvs64893** [comment]
@boothen 
New version is working fine, thank you!
